name: flutter build ios

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

  workflow_dispatch:


jobs:

  flutter_build_ios:
    build:
      runs-on: macos-latest
      timeout-minutes: 5
      steps:
        - uses: actions/checkout@v3
        - uses: subosito/flutter-action@v2
          with:
            flutter-version: '2.8.1'
            architecture: x64
        - run: flutter pub get
        - run: flutter test
        - run: flutter build ios --release --no-codesign